/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack;

import java.io.*;

import java.util.Formatter;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.plaf.RootPaneUI;

/**
 *
 * @author Marvkare
 */
public class Editar extends javax.swing.JPanel {
    String barra = File.separator;
    String ubicacion =  System.getProperty("user.dir")+barra+"registros"+barra;
    
    public void Buscar(){
       
   
        File url = new File(ubicacion+Buscartf.getText()+".txt");
        if(Buscartf.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Indique en el libro para mostrar");
            
        }else{
            if(url.exists()){
                try {
                    FileInputStream fis = new FileInputStream(url);
                    Properties mostrar = new Properties();
                    mostrar.load(fis);
                    
                    
                    Nombretf.setText(mostrar.getProperty("Nombre"));
                    Autortf.setText(mostrar.getProperty("Autor"));        
                    Editorialtf.setText(mostrar.getProperty("Editorial"));
                    Generotf.setText(mostrar.getProperty("Genero"));
                    Añotf.setText(mostrar.getProperty("Ano"));
                    Prestadotf.setText(mostrar.getProperty("Prestado"));
                } catch (Exception e) {
                }
            } else{
                JOptionPane.showMessageDialog(null, "Ese libro no esta registrado");
            }
        }
        
        
    
    }
    public void editar (){
        File url = new File(ubicacion+Buscartf.getText()+".txt");
        
        if(Buscartf.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Indique el registr ha editar");
        }else{
            if (url.exists()){
            try {
                String btns [] ={"Eliminar ","Cancelar"};
                if(!((Buscartf.getText()+".txt").equals(Nombretf.getText()+".txt")) ){
                    
                    Formatter crea = new Formatter(ubicacion+Nombretf.getText()+".txt");
                    
                        FileInputStream Archivod = new FileInputStream(url);
                    Archivod.close();
                    System.gc();
                    
                        System.out.println("Se elimino el archivo");
                    
                    
                    
                }
                url.delete();
                String nombre = "Nombre=";
                Buscartf.setText(Nombretf.getText());
                FileWriter permite_escrito = new FileWriter(ubicacion+Buscartf.getText()+".txt");
               
                String autor = "Autor=";
                String editorial = "Editorial=";
                String año = "Ano=";
                String genero = "Genero="; 
                String prestamos = "Prestado=";
                String name = Buscartf.getText()+".txt";
                PrintWriter guardar  = new PrintWriter(permite_escrito);
                guardar.println(nombre+Nombretf.getText());
                guardar.println(autor+Autortf.getText());
                guardar.println(editorial+Editorialtf.getText());
                guardar.println(año+Añotf.getText());
                guardar.println(genero+Generotf.getText());
                guardar.println(prestamos+Generotf.getText());
                
                permite_escrito.close();
                
                
                
                
                JOptionPane.showMessageDialog(null, "Registro editado correctamente");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error "+ e);
            }
            }else{
            JOptionPane.showMessageDialog(null, "El Registro no existe");
            }
            
                   
            
        }

}
            
    public Editar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nombretf = new javax.swing.JTextField();
        Autortf = new javax.swing.JTextField();
        Generotf = new javax.swing.JTextField();
        Añotf = new javax.swing.JTextField();
        Editorialtf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Buscartf = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Prestadotf = new javax.swing.JTextField();

        jLabel1.setText("Nombre");

        jLabel2.setText("Editorial");

        jLabel3.setText("Genero");

        jLabel4.setText("Autor");

        jLabel5.setText("Año");

        Nombretf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombretfActionPerformed(evt);
            }
        });

        Autortf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutortfActionPerformed(evt);
            }
        });

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Buscartf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscartfActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Prestado?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Buscartf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Nombretf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(Editorialtf)
                                    .addComponent(Generotf))
                                .addGap(45, 45, 45)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Autortf)
                            .addComponent(jLabel4)
                            .addComponent(Añotf)
                            .addComponent(jLabel6)
                            .addComponent(Prestadotf, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscartf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nombretf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(Editorialtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(Generotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Autortf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)
                                .addComponent(Añotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel6)
                        .addGap(9, 9, 9)
                        .addComponent(Prestadotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NombretfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombretfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombretfActionPerformed

    private void AutortfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutortfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutortfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      editar();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Buscar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BuscartfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscartfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscartfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Autortf;
    private javax.swing.JTextField Añotf;
    private javax.swing.JTextField Buscartf;
    private javax.swing.JTextField Editorialtf;
    private javax.swing.JTextField Generotf;
    private javax.swing.JTextField Nombretf;
    private javax.swing.JTextField Prestadotf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
